language: java
script:
- TERM=dumb ./gradlew clean check

jdk:
  - openjdk6
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env:
  global:
  - secure: mn5HXRqI8btBN76tIfrxeC6aLrXSgEuTVMA7ZuZLF7jwbTZkrs0rELFeAUNU0vjkW5gq3yKgV/WB0fhSFAMGGp44lrfOC0GB24lH3OaQWQQJcU7EKc7q/xvc65o9UbUTqxOoCBcQsqFaGSh7Op94mtR7h10Lbf7r69OcngOgt70=
  - secure: i/GulSx1wbhHph7erloWXpdDunyqlKrWhEHqeEQeCn9BGVsJhBXtx/QWC03HtbvBg+tRGjHGQeiNfesbxBgVN87Vt3D8l8T6DygIVt9K2IDRtdm97gVf7P3tFi0PRRqTBT63eyXwymiMzxVOQC01OuLOHn4Y+HEFn80sdc+0WpA=
  - secure: jBmnnTVwrBwUNPhSiMey0HRQ9Df7qmb+QLcMFi8ivQy7vh8WKm2ovkyzfMEg5Ci/ZVpwCm5Pbaaa5w1LqTJPnfHtRxO11nUBeJCwqwhWcSep19RLuW65JEVgLncn2SCtYHaPodWm+VSjnr/p98x6Tk0ZLkREEZd8ZldNtq8ZEO8=
