codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...95"

  status:
    project: yes
    patch: yes
    changes: no
    
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/49ad46bbe08a7cda7e7f"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: null

ignore:
  - "springfox-petstore"  # ignore petstore project as its a sample
  - "springfox-petstore-webflux"  # ignore petstore project as its a sample
  - "springfox-spring-config" # ignore project used for documentation
  - "swagger-contract-tests" # ignore contract tests as its purely for testing
  - "swagger-contract-tests-webflux" # ignore contract tests as its purely for testing
  - "oas-contract-tests" # ignore contract tests as its purely for testing
  - "springfox-boot-starter" # ignore contract tests as its purely for testing

